# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import video_stream_pb2 as video__stream__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in video_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FallDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamDetection = channel.stream_stream(
                '/FallDetectionService/StreamDetection',
                request_serializer=video__stream__pb2.VideoFrame.SerializeToString,
                response_deserializer=video__stream__pb2.DetectionResult.FromString,
                _registered_method=True)
        self.DetectFrame = channel.unary_unary(
                '/FallDetectionService/DetectFrame',
                request_serializer=video__stream__pb2.VideoFrame.SerializeToString,
                response_deserializer=video__stream__pb2.DetectionResult.FromString,
                _registered_method=True)


class FallDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamDetection(self, request_iterator, context):
        """双向流式检测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFrame(self, request, context):
        """单帧检测（备用）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FallDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamDetection': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamDetection,
                    request_deserializer=video__stream__pb2.VideoFrame.FromString,
                    response_serializer=video__stream__pb2.DetectionResult.SerializeToString,
            ),
            'DetectFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFrame,
                    request_deserializer=video__stream__pb2.VideoFrame.FromString,
                    response_serializer=video__stream__pb2.DetectionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FallDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FallDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FallDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamDetection(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/FallDetectionService/StreamDetection',
            video__stream__pb2.VideoFrame.SerializeToString,
            video__stream__pb2.DetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FallDetectionService/DetectFrame',
            video__stream__pb2.VideoFrame.SerializeToString,
            video__stream__pb2.DetectionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
